Fix Keras version
Otherwise, the lastest Keras will be installed,  and it will cause the
version mismatch with TensorFlow, resulting in the following error:
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[1], line 1
----> 1 from utils import get_dataset

File /app/project/utils.py:4
      1 import logging
      3 import tensorflow.compat.v1 as tf
----> 4 from object_detection.inputs import train_input
      5 from object_detection.protos import input_reader_pb2
      6 from object_detection.builders.dataset_builder import build as build_dataset

File /usr/local/lib/python3.8/dist-packages/object_detection/inputs.py:27
     25 from object_detection.builders import dataset_builder
     26 from object_detection.builders import image_resizer_builder
---> 27 from object_detection.builders import model_builder
     28 from object_detection.builders import preprocessor_builder
     29 from object_detection.core import box_list

File /usr/local/lib/python3.8/dist-packages/object_detection/builders/model_builder.py:37
     35 from object_detection.meta_architectures import center_net_meta_arch
     36 from object_detection.meta_architectures import context_rcnn_meta_arch
---> 37 from object_detection.meta_architectures import deepmac_meta_arch
     38 from object_detection.meta_architectures import faster_rcnn_meta_arch
     39 from object_detection.meta_architectures import rfcn_meta_arch

File /usr/local/lib/python3.8/dist-packages/object_detection/meta_architectures/deepmac_meta_arch.py:20
     18 from object_detection.meta_architectures import center_net_meta_arch
     19 from object_detection.models.keras_models import hourglass_network
---> 20 from object_detection.models.keras_models import resnet_v1
     21 from object_detection.protos import center_net_pb2
     22 from object_detection.protos import losses_pb2

File /usr/local/lib/python3.8/dist-packages/object_detection/models/keras_models/resnet_v1.py:21
     19 from __future__ import division
     20 from __future__ import print_function
---> 21 from keras.applications import resnet
     23 import tensorflow.compat.v1 as tf
     25 from object_detection.core import freezable_batch_norm

File /usr/local/lib/python3.8/dist-packages/keras/__init__.py:3
      1 """AUTOGENERATED. DO NOT EDIT."""
----> 3 from keras import __internal__
      4 from keras import activations
      5 from keras import applications

File /usr/local/lib/python3.8/dist-packages/keras/__internal__/__init__.py:3
      1 """AUTOGENERATED. DO NOT EDIT."""
----> 3 from keras.__internal__ import backend
      4 from keras.__internal__ import layers
      5 from keras.__internal__ import losses

File /usr/local/lib/python3.8/dist-packages/keras/__internal__/backend/__init__.py:3
      1 """AUTOGENERATED. DO NOT EDIT."""
----> 3 from keras.src.backend import _initialize_variables as initialize_variables
      4 from keras.src.backend import track_variable

File /usr/local/lib/python3.8/dist-packages/keras/src/__init__.py:21
     15 """Implementation of the Keras API, the high-level API of TensorFlow.
     16
     17 Detailed documentation and user guides are available at
     18 [keras.io](https://keras.io).
     19 """
     20 from keras.src import distribute
---> 21 from keras.src import models
     22 from keras.src.engine.input_layer import Input
     23 from keras.src.engine.sequential import Sequential

File /usr/local/lib/python3.8/dist-packages/keras/src/models/__init__.py:18
      1 # Copyright 2022 The TensorFlow Authors. All Rights Reserved.
      2 #
      3 # Licensed under the Apache License, Version 2.0 (the "License");
   (...)
     13 # limitations under the License.
     14 # ==============================================================================
     15 """Keras models API."""
---> 18 from keras.src.engine.functional import Functional
     19 from keras.src.engine.sequential import Sequential
     20 from keras.src.engine.training import Model

File /usr/local/lib/python3.8/dist-packages/keras/src/engine/functional.py:25
     21 import warnings
     23 import tensorflow.compat.v2 as tf
---> 25 from keras.src import backend
     26 from keras.src.dtensor import layout_map as layout_map_lib
     27 from keras.src.engine import base_layer

File /usr/local/lib/python3.8/dist-packages/keras/src/backend.py:34
     32 from keras.src import backend_config
     33 from keras.src.distribute import distribute_coordinator_utils as dc
---> 34 from keras.src.dtensor import dtensor_api as dtensor
     35 from keras.src.engine import keras_tensor
     36 from keras.src.utils import control_flow_util

File /usr/local/lib/python3.8/dist-packages/keras/src/dtensor/__init__.py:22
     20 # Conditional import the dtensor API, since it is currently broken in OSS.
     21 if _DTENSOR_API_ENABLED:
---> 22     from tensorflow.compat.v2.experimental import dtensor as dtensor_api
     23 else:
     24     # Leave it with a placeholder, so that the import line from other python
     25     # file will not break.
     26     dtensor_api = None

ImportError: cannot import name 'dtensor' from 'tensorflow.compat.v2.experimental' (/usr/local/lib/python3.8/dist-packages/tensorflow/_api/v2/compat/v2/experimental/__init__.py)